# Generated by Django 3.0.2 on 2020-01-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a transaction category (e.g. Food)', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CCY',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a short name for a currency (e.g. RUB)', max_length=10)),
                ('full_name', models.CharField(help_text='Enter a full name for a currency (e.g. Russian ruble)', max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tr_date', models.DateField()),
                ('tr_time', models.DateField(blank=True, null=True)),
                ('Sum', models.DecimalField(decimal_places=10, help_text='Enter a transaction sum (e.g. 500.0, or -50.5 for receiving)', max_digits=19)),
                ('tr_direction', models.CharField(blank=True, choices=[('+', 'Spending'), ('-', 'Obtaining')], default='+', help_text="Whether you're spending (+) or receiving (-)", max_length=1)),
                ('Content', models.CharField(help_text='Enter a transaction category (e.g. Food)', max_length=200)),
                ('CCY', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hbpapp.CCY')),
                ('Category', models.ManyToManyField(help_text='Select a Category for this transaction', to='hbpapp.Category')),
            ],
            options={
                'ordering': ['tr_date', 'tr_time'],
            },
        ),
    ]
