# Generated by Django 3.0.2 on 2020-01-08 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hbpapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Sum',
            field=models.DecimalField(decimal_places=2, help_text='Enter a transaction sum', max_digits=19),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='tr_direction',
            field=models.CharField(blank=True, choices=[('-', 'Spending'), ('+', 'Obtaining')], default='+', help_text="Whether you're spending (-) or receiving (+)", max_length=1),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='tr_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
