# Project configuiration for Python tools.
[tool.black]
target-version = ["py38"]
line-length = 120

[tool.isort]
py_version = "38"
line_length = 120
profile = "black"
from_first = true
skip_gitignore = true
